Q1.A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units.
A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% 
significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

Solution: 
Here we will use 2 sample t test.

Null hypothesis(H0): Data are normal (p-value>alpha)
Alternate hypothesis(H1): Data are not normal (p-value<alpha)



In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("D:\\Assignment datasets\\Cutlets.csv")
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [8]:
#Normality test:
#Normality test for unit A
#For unit A;
from scipy.stats import shapiro
statistic,pvalue = shapiro(df["Unit A"])
print(pvalue)

alpha = 0.05

if pvalue<alpha:
    print("Ho is rejected and H1 is accepted")
else:
    print("Ho is accepted and H1 is rejected")



0.3199819028377533
Ho is accepted and H1 is rejected


In [9]:
#For unit B; 
from scipy.stats import shapiro
statistic,pvalue = shapiro(df["Unit B"])
print(pvalue)

alpha = 0.05

if pvalue<alpha:
    print("Ho is rejected and H1 is accepted")
else:
    print("Ho is accepted and H1 is rejected")



0.5224985480308533
Ho is accepted and H1 is rejected


In [ ]:
# Two sample t- test

Null hypothesis(H0): µ1= µ2 (population mean of unit A is equal to unit B)
Alternate hypothesis(H1): µ1≠ µ2 (population mean of unit A is not equal to unit B)


In [10]:
from scipy import stats
from scipy import stats as twosample

zcalc, pval = twosample.ttest_ind(df["Unit A"] ,df["Unit B"])

print("zcalculated value: ",zcalc)
print("p-value: ",pval)

alpha = 0.05

if pvalue<alpha:
    print("Ho is rejected and H1 is accepted")
else:
    print("Ho is accepted and H1 is rejected")


zcalculated value:  0.7228688704678063
p-value:  0.4722394724599501
Ho is accepted and H1 is rejected


In [ ]:
Results:

The p-value of two sample t-test is equals to 0.4722 which is greater than the significance level alpha(0.05).
Hence, null hypothesis accepted.

This implies that we can say that the population mean of Unit A is statistically not different from population mean of Unit B.


In [ ]:
Q2.A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the
laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories.
TAT is defined as sample collected to report dispatch.
   
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% 
significance level.
 Minitab File: LabTAT.mtw

Solution:
Here we will use ANOVA-one way test.

Hypothesis:
Null hypothesis(H0): µ1= µ2 = µ3 = µ4(All the averages are same)
Alternate hypothesis(H1): At least one labs average TAT is different


In [12]:
import pandas as pd
df = pd.read_csv("D:\\Assignment datasets\\LabTAT.csv")
df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [13]:
# FTABLE VALUE 
import scipy.stats as ftable
ft = ftable.f(dfn=3, dfd=476)
ft.ppf(0.95).round(4)


2.6236

In [19]:
#ANOVA
import scipy.stats as stats
Fcalc, p = stats.f_oneway(df.iloc[:,0], df.iloc[:,1], df.iloc[:,2], df.iloc[:,3])
Fcalc

118.70421654401437

In [20]:
alpha = 0.05
print(p)
if p < alpha:
    print("Ho is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 is accepted")


2.1156708949992414e-57
Ho is rejected and H1 is accepted


In [ ]:
Results :
Hence, from the above calculations we can see Fcalc = 118.7042 and p-value = 2.12E-57 i.e., 0.00 which is less than the 
significance level that is alpha(0.05).
pvalue<alpha (0.00<0.05)
Hence, rejected null hypothesis i.e., H1 is accepted.

Statistically, all the average TAT of the laboratories are not same. There is the significance difference among the averages.


In [ ]:
Q3.Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are 
similar across regions.
Minitab File: BuyerRatio.mtw

Solution: 
Here we will use Chi-square hypothesis test.

Hypothesis:
Null hypothesis(H0): The male female buyer ratios are similar across all the regions i.e., all the proportions are equal.
Alternate hypothesis(H1): The male female buyer ratios not similar across all the regions i.e.,
not all the proportions are equal.


In [1]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

In [2]:
df = pd.read_csv("D:\\Assignment datasets\\BuyerRatio.csv")

In [3]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
observed = np.array([[50,142,131,70], [435,1523,1356,750]])

In [5]:
chi_val, p_val, dof, expected = chi2_contingency(observed)

In [6]:
chi_val, p_val, dof, expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [7]:
chi_val, p_val, dof, expected = chi2_contingency(observed, correction=False)
chi_val, p_val, dof, expected 

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [8]:
alpha=0.05

if 0.66<alpha:
    print("Ho is rejected and H1 is accepted")
else:
    print("H1 is rejected and Ho is accepted")


H1 is rejected and Ho is accepted


In [10]:
#chi square table value
import scipy.stats as stats
chi_table=stats.chi2.ppf(q=0.95, df=3)
chi_table.round(4)



7.8147

In [ ]:
Results:

As we can see above p value is greater than alpha hence we will fail to reject H0 (null hypothesis) here.
pvalue > alpha (0.66>0.05)

Accept H0 =>  The male female buyer ratios are similar across the regions i.e., All the proportions are equal.

In [ ]:
Q4.TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms.
Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the
defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate
inferences

Minitab File: CustomerOrderForm.mtw
 

Solution: 
Here we will use Chi-square hypothesis test.

Hypothesis:
Null hypothesis(H0): The defective % does not vary by centre / the variables are independent
Alternate hypothesis(H1): The defective % does vary by centre / the variables are dependent
     

In [30]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy import stats
from scipy.stats import chi2_contingency

In [12]:
df2 = pd.read_csv("D:\\Assignment datasets\\Costomer+OrderForm.csv")
df2.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [13]:
df2.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [14]:
df2.dtypes

Phillippines    object
Indonesia       object
Malta           object
India           object
dtype: object

In [15]:
table = [[271,267,269,280], [29,33,31,20]]

In [21]:
data1 = pd.DataFrame([[271,267,269,280], [29,33,31,20]], 
                     index = ['Error Free', 'Defective'], columns = ['Phillippines', 'Indonesia', 'Malta', 'India'])
data1

Phillippines  Indonesia  Malta  India
Error Free           271        267    269    280
Defective             29         33     31     20

In [33]:
observed = np.array([[271,267,269,280], [29,33,31,20]])

In [34]:
chi_val, p_val, dof, expected = chi2_contingency(observed)

In [35]:
chi_val, p_val, dof, expected 

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [36]:
alpha=0.05

if 0.277<alpha:
    print("Ho is rejected and H1 is accepted")
else:
    print("H1 is rejected and Ho is accepted")


H1 is rejected and Ho is accepted


In [37]:
#chi square table value
import scipy.stats as stats
chi_table=stats.chi2.ppf(q=0.95, df=3)
chi_table.round(4)


7.8147

In [ ]:
Results:
As we can see above p value is greater than alpha hence we will fail to reject H0 (null hypothesis) here.
pvalue > alpha (0.277>0.05)

Accept Null hypothesis(H0): The defective % does not vary by centre / the variables are independent